### ISSUE TITLE
slow on the installs

### ISSUE THREAD

**Issue by franz101** [jerry-git/pytest-split-gh-actions-demo#4]
Is there a way to have the installs run first and then start the parallel workflow?

**Comment by jerry-git** [comment]
What do you mean by "installs"?

**Comment by franz101** [comment]
hey jerry :),
I meant:
pip install requirements

Currently the installs take 4 minutes for each split test

**Comment by franz101** [comment]
Create a cache beforehand with:

A potential idea for really slow installs:
https://github.com/actions/setup-python/issues/330#issuecomment-1500667578
